CREATE TABLE Client (
  id BIGINT AUTO_INCREMENT NOT NULL,
   firstName VARCHAR(255) NOT NULL,
   lastNAme VARCHAR(255) NOT NULL,
   cpf VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   zipCode VARCHAR(255) NOT NULL,
   street VARCHAR(255) NOT NULL,
   CONSTRAINT pk_client PRIMARY KEY (id)
);

ALTER TABLE Client ADD CONSTRAINT uc_client_cpf UNIQUE (cpf);

ALTER TABLE Client ADD CONSTRAINT uc_client_email UNIQUE (email);